# Generated by Django 4.1.7 on 2023-03-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_event_registration_event_attendees_event_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('food', 'Food'), ('sports', 'Sports'), ('other', 'Other')], default='Music', max_length=10),
        ),
    ]
