# Generated by Django 4.1.7 on 2023-03-12 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_event_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='user',
            new_name='participant',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
    ]
