# Generated by Django 4.1.7 on 2023-03-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_user_registration_participant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='participant',
            new_name='user',
        ),
    ]
