# Generated by Django 4.1.7 on 2023-03-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_participant_registration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
