# Generated by Django 4.1.7 on 2023-03-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_event_end_time_event_start_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
