# Generated by Django 4.1.7 on 2023-03-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_event_featured_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('health', 'Health'), ('tech', 'Tech'), ('hobbies', 'Hobbies'), ('business', 'Business'), ('sports', 'Sports'), ('food', 'Food and Eat'), ('arts', 'Visual Arts')], default='Music', max_length=10),
        ),
    ]
